export const siteData = {
  brand: {
    name: "AXF",
    fullName: "Axiom Wrestling Federation",
    tagline: "Where Power Becomes Legacy",
    continuity: "Continuity locked through Season 3, Episode 9.",
  },
  nav: [
    { label: "Home", href: "./index.html", key: "home" },
    { label: "Superstars", href: "./superstars.html", key: "superstars" },
    { label: "Champions", href: "./champions.html", key: "champions" },
    { label: "Premium Live Events", href: "./events.html", key: "events" },
    { label: "News", href: "./news.html", key: "news" },
    { label: "Storylines", href: "./storylines.html", key: "storylines" },
    { label: "Hall of Legends", href: "./legends.html", key: "legends" },
    { label: "Media", href: "./media.html", key: "media" },
    { label: "Gallery", href: "./gallery.html", key: "gallery" },
    { label: "About AXF", href: "./about.html", key: "about" },
    { label: "Contact", href: "./contact.html", key: "contact" },
  ],
  ticker: [
    "Breaking: Danny's influence continues to reshape the AXF power structure.",
    "Official: Logan Mathews remains the lead challenger in pursuit of Austin.",
    "Backlash Focus: Damian Cooper prepares for the defining test of his ascent against Danny.",
    "Champion Watch: Tyson Creed stands as the verified Intercontinental Champion.",
    "Continuity Note: All records on this platform are locked through Season 3, Episode 9.",
  ],
  heroStats: [
    { value: "12", label: "World titles for Danny" },
    { value: "9", label: "WrestleMania main events" },
    { value: "1", label: "Power center taking shape" },
  ],
  featuredSpotlights: [
    {
      id: "danny",
      name: "Danny",
      title: "The God of Reckoning",
      subtitle: "Legend. Executive. Final Boss.",
      blurb:
        "AXF's most feared competitor is no longer only controlling the ring. Danny's rise inside the corporate structure is turning every decision into a fight for the soul of the company.",
      image: "./assets/roster/danny.png",
      accent: "gold",
      cta: "./storylines.html",
    },
    {
      id: "jayden",
      name: "Jayden",
      title: "The Architect of Survival",
      subtitle: "Veteran mentor with unfinished history.",
      blurb:
        "Jayden knows better than anyone what it costs to stand beside Danny and what it means to fall behind him. Now he is investing that experience into Damian Cooper.",
      image: "./assets/roster/jayden.png",
      accent: "silver",
      cta: "./superstars.html#jayden",
    },
    {
      id: "austin",
      name: "Austin",
      title: "Corporate Standard",
      subtitle: "Champion with power at his back.",
      blurb:
        "Austin sits atop the championship picture as a ruthless corporate heel, carrying the confidence of a champion and the protection of a machine that believes he is the future.",
      image: "./assets/roster/austin.png",
      accent: "crimson",
      cta: "./champions.html",
    },
    {
      id: "logan-mathews",
      name: "Logan Mathews",
      title: "Main Event Heir",
      subtitle: "The next face of AXF.",
      blurb:
        "Logan Mathews refuses to bow to the politics around the title scene. Every appearance feels like a message to Austin and a preview of the man many believe can carry AXF forward.",
      image: "./assets/roster/logan-mathews.png",
      accent: "gold",
      cta: "./storylines.html#logan-vs-austin",
    },
    {
      id: "damian-cooper",
      name: "Damian Cooper",
      title: "The Proof of Potential",
      subtitle: "Protégé under pressure.",
      blurb:
        "Damian Cooper entered this chapter as a champion and now steps toward Backlash with Jayden's guidance, a target on his back, and Danny waiting to measure him.",
      image: "./assets/roster/damian-cooper.png",
      accent: "silver",
      cta: "./storylines.html#damian-vs-danny",
    },
  ],
  rivalries: [
    {
      headline: "Logan Mathews vs Austin",
      tone: "World title pressure",
      summary:
        "Austin rules the title picture through authority-backed control. Logan is forcing the company to answer whether the top prize belongs to power or to performance.",
    },
    {
      headline: "Danny vs The Authority Structure",
      tone: "Corporate war",
      summary:
        "Danny's ascent is no longer symbolic. Every move against TKO-aligned control pushes AXF closer to a new center of influence.",
    },
    {
      headline: "Damian Cooper vs Danny",
      tone: "Backlash proving ground",
      summary:
        "This is not a grudge for the future. It is an immediate test of whether Damian can survive the pressure of facing AXF's most complete force.",
    },
    {
      headline: "Camron Carter vs Austin's past",
      tone: "Authority scars",
      summary:
        "Camron Carter carries history with Austin and the structure that helped build him. Every confrontation feels like unfinished business finding its moment.",
    },
  ],
  results: [
    {
      event: "AXF Television",
      match: "Logan Mathews def. Benjamin Carter",
      note: "Momentum builder in the race toward Austin.",
    },
    {
      event: "AXF Television",
      match: "Tyson Creed retained the Intercontinental Championship",
      note: "The champion continues to add weight to the division.",
    },
    {
      event: "AXF Television",
      match: "Damian Cooper stood tall after a chaotic closing segment",
      note: "Jayden's mentorship remains central before Backlash.",
    },
  ],
  promoOfWeek: {
    title: "Power. Legacy. Destiny.",
    speaker: "Danny",
    summary:
      "AXF's defining voice made it clear that influence is no longer borrowed. The era is shifting, and the people who cannot adapt will be forced to move around him.",
  },
  champions: [
    {
      title: "AXF Championship",
      division: "World Title",
      champion: "Jayden",
      status: "Verified active champion",
      reign: "Official reign active",
      defenses: "On-screen defenses continue under current broadcast record",
      prestige:
        "The flagship prize of the company and one of the clearest symbols of Jayden's all-time main-event standing.",
      historyNote: "Title history archive expands only through confirmed Season 3 Episode 9 records.",
      accent: "gold",
    },
    {
      title: "World Heavyweight Championship",
      division: "World Title",
      champion: "Jayden",
      status: "Verified active champion",
      reign: "Official reign active",
      defenses: "Recognized defenses under current continuity",
      prestige:
        "A premier world championship that reinforces Jayden's place at the top of AXF's competitive hierarchy.",
      historyNote: "Listed directly per the confirmed update for this build.",
      accent: "silver",
    },
    {
      title: "Intercontinental Championship",
      division: "Midcard Title",
      champion: "Tyson Creed",
      status: "Verified active champion",
      reign: "Official reign active",
      defenses: "Recognized televised defenses within current continuity",
      prestige:
        "AXF's proving-ground title for athletes who demand prime-time spotlight and championship-level pressure.",
      historyNote: "Tyson Creed is the only confirmed Intercontinental Champion displayed on this build.",
      accent: "gold",
    },
    {
      title: "United States Championship",
      division: "Midcard Title",
      champion: "Damian Cooper",
      status: "Verified at the beginning of the current arc",
      reign: "Active through the current chapter",
      defenses: "Current on-screen status preserved without future spoilers",
      prestige:
        "A title built around hunger, visibility, and the ability to carry momentum into the main-event picture.",
      historyNote: "Displayed in direct connection to Damian Cooper's active rise.",
      accent: "silver",
    },
    {
      title: "AXF Tag Team Championships",
      division: "Tag Team",
      champion: "Camron Carter and Benjamin Carter",
      status: "Verified active champions",
      reign: "Official reign active",
      defenses: "Recognized televised defenses within current continuity",
      prestige:
        "A division built on chemistry, strategy, and timing, currently anchored by Camron Carter and Benjamin Carter.",
      historyNote: "Current titleholders listed directly per the confirmed update for this build.",
      accent: "gold",
    },
    {
      title: "Women's World Championship",
      division: "Women's Title",
      champion: "Official records update pending",
      status: "Unverified holder withheld to protect canon",
      reign: "Pending verified count",
      defenses: "Pending verified ledger",
      prestige:
        "One of AXF's premier championships, protected from inaccurate listing until verified records are supplied.",
      historyNote: "No speculative champion is shown.",
      accent: "crimson",
    },
  ],
  roster: [
    {
      id: "danny",
      tier: "Main Event",
      name: "Danny",
      moniker: "The God of Reckoning",
      hometown: "Valhalla Crown Studios",
      age: "26",
      alignment: "Complex power figure",
      image: "./assets/roster/danny.png",
      initials: "DR",
      championshipHistory: "12-time World Champion, Royal Rumble winner, nine-time WrestleMania main eventer",
      signatureMove: "Royal Verdict",
      finisher: "Reckoning Driver",
      rivalries: "Authority structure, Austin, Damian Cooper",
      achievements: "The most decorated active figure in AXF and the company's central gravitational force",
      storylineStatus: "Beginning his CEO power rise while tightening his grip over every major conversation in AXF",
      motivation: "To turn legendary status into institutional power without losing the aura that made him untouchable",
      spotlight: "Legend + Executive + Final Boss",
    },
    {
      id: "jayden",
      tier: "Main Event",
      name: "Jayden",
      moniker: "The Architect of Survival",
      hometown: "Chicago, Illinois",
      age: "30",
      alignment: "Face",
      image: "./assets/roster/jayden.png",
      initials: "JY",
      championshipHistory: "Multiple main-event title runs across AXF's modern era",
      signatureMove: "Cipher Kick",
      finisher: "Echo Collapse",
      rivalries: "Danny, Damian's doubters, institutional pressure",
      achievements: "A generation-defining main-eventer whose history with Danny is layered with betrayals, reunions, and unfinished emotion",
      storylineStatus: "Mentoring Damian Cooper while carrying the scars of always being measured against Danny",
      motivation: "To prove his legacy is not secondary to Danny's and to prepare Damian for the wars ahead",
      spotlight: "An all-time star who knows what it costs to live in Danny's shadow",
    },
    {
      id: "austin",
      tier: "Main Event",
      name: "Austin",
      moniker: "Corporate Standard",
      hometown: "Los Angeles, California",
      age: "29",
      alignment: "Heel",
      image: "./assets/roster/austin.png",
      initials: "AU",
      championshipHistory: "Current AXF Champion and centerpiece of the company-backed title picture",
      signatureMove: "Boardroom Knee",
      finisher: "Hostile Takeover",
      rivalries: "Logan Mathews, Danny, Camron Carter",
      achievements: "One of the company's most protected titleholders and its most visible antagonist in the championship scene",
      storylineStatus: "Maintaining control as the corporate heel champion while challengers keep closing in",
      motivation: "To weaponize prestige, politics, and pressure until no challenger can expose a weakness",
      spotlight: "The champion who treats power like part of the entrance",
    },
    {
      id: "logan-mathews",
      tier: "Main Event",
      name: "Logan Mathews",
      moniker: "The Punisher",
      hometown: "Phoenix, Arizona",
      age: "28",
      alignment: "Face",
      image: "./assets/roster/logan-mathews.png",
      initials: "LM",
      championshipHistory: "Main-event contender with a clear path into the world-title spotlight",
      signatureMove: "Valley Rush",
      finisher: "Punishment Protocol",
      rivalries: "Austin, the system protecting Austin",
      achievements: "Viewed across AXF as the next major babyface and a future heir to Danny's level of command",
      storylineStatus: "The top challenger pressing directly into Austin's title orbit",
      motivation: "To prove the future face of AXF can be built on merit instead of corporate preference",
      spotlight: "The next major face of AXF, not a parody, not a side act",
    },
    {
      id: "damian-cooper",
      tier: "Main Event",
      name: "Damian Cooper",
      moniker: "D.C.",
      hometown: "Miami, Florida",
      age: "24",
      alignment: "Face",
      image: "./assets/roster/damian-cooper.png",
      initials: "DC",
      championshipHistory: "Champion at the start of the current arc and one of the fastest-rising singles stars in AXF",
      signatureMove: "Cooper Clutch",
      finisher: "Dead Center",
      rivalries: "Danny, his own pressure ceiling",
      achievements: "Protected as a genuine prospect with championship credibility instead of a rushed shortcut",
      storylineStatus: "Preparing for Danny at Backlash with Jayden in his corner and enormous expectation on his shoulders",
      motivation: "To prove mentorship can sharpen greatness without turning him into a copy of the man who trained him",
      spotlight: "A rising singles star whose next test could change his ceiling",
    },
    {
      id: "titan-cross",
      tier: "Upper Midcard",
      name: "Titan Cross",
      moniker: "The Island Machine",
      hometown: "Kona, Hawaii",
      age: "31",
      alignment: "Tweener",
      image: "./assets/roster/titan-cross.png",
      initials: "TC",
      championshipHistory: "Former featured contender with main-event level physical credibility",
      signatureMove: "Tidal Crush",
      finisher: "Cross Current Bomb",
      rivalries: "Any athlete trying to outrun his pace",
      achievements: "A powerhouse presence who turns every collision into a headline segment",
      storylineStatus: "Circling the upper tier with the sense that one marquee victory could relaunch him into title contention",
      motivation: "To remind the roster that force still matters in an era obsessed with politics",
      spotlight: "Kona power with stadium aura",
    },
    {
      id: "camron-carter",
      tier: "Upper Midcard",
      name: "Camron Carter",
      moniker: "The Pressure Point",
      hometown: "Atlanta, Georgia",
      age: "29",
      alignment: "Face",
      image: "./assets/roster/camron-carter.png",
      initials: "CC",
      championshipHistory: "Featured singles competitor with history tied closely to Austin and the TKO Authority environment",
      signatureMove: "Carter Breaker",
      finisher: "Redline Trigger",
      rivalries: "Austin, the culture that helped protect Austin",
      achievements: "A high-value roster talent whose history makes him impossible to separate from the current authority-era tension",
      storylineStatus: "Watching the title picture closely while old fractures with Austin remain very much alive",
      motivation: "To make the system answer for every opportunity it denied him",
      spotlight: "History, rage, and purpose in one frame",
    },
    {
      id: "benjamin-carter",
      tier: "Upper Midcard",
      name: "Benjamin Carter",
      moniker: "The Silent Standard",
      hometown: "Dallas, Texas",
      age: "27",
      alignment: "Heel",
      image: "./assets/roster/benjamin-carter.png",
      initials: "BC",
      championshipHistory: "A polished roster threat with credible singles upside",
      signatureMove: "Blackout Lariat",
      finisher: "Executive Silence",
      rivalries: "Logan Mathews, anyone trying to outwork him",
      achievements: "Built as a legitimate television presence with a cold, composed ring identity",
      storylineStatus: "Hovering around breakthrough territory and dangerous enough to disrupt the wrong contender at the wrong time",
      motivation: "To convert respect into leverage and leverage into a bigger place on the card",
      spotlight: "A controlled threat with premium television instincts",
    },
    {
      id: "matthew-cross",
      tier: "Upper Midcard",
      name: "Matthew Cross",
      moniker: "The Divide",
      hometown: "Cleveland, Ohio",
      age: "28",
      alignment: "Tweener",
      image: "./assets/roster/matthew-cross.png",
      initials: "MC",
      championshipHistory: "Upper-tier contender known for dragging rivals into exacting fights",
      signatureMove: "Split Decision Kick",
      finisher: "Cross Examination",
      rivalries: "Technical strikers and loudmouth opportunists alike",
      achievements: "Consistently credible, endlessly dangerous, and difficult to prepare for",
      storylineStatus: "Lurking just beneath the marquee layer, ready to punish distraction",
      motivation: "To force the spotlight to respect precision as much as spectacle",
      spotlight: "A disruptor who can ruin a plan in one opening",
    },
    {
      id: "tyson-creed",
      tier: "Upper Midcard",
      name: "Tyson Creed",
      moniker: "The Iron Reign",
      hometown: "Detroit, Michigan",
      age: "30",
      alignment: "Heel",
      image: "./assets/roster/tyson-creed.png",
      initials: "TY",
      championshipHistory: "Current Intercontinental Champion",
      signatureMove: "Steel Frame Spinebuster",
      finisher: "Creedfall",
      rivalries: "Every contender in the Intercontinental field",
      achievements: "Recognized champion with the kind of physical credibility that makes the title feel heavier",
      storylineStatus: "Holding the Intercontinental Championship and making the division revolve around him",
      motivation: "To transform a title reign into proof that he belongs higher on the mountain",
      spotlight: "Championship-level intensity with no wasted motion",
    },
  ],
  events: [
    {
      name: "Backlash",
      window: "Up Next",
      venue: "Venue to be announced",
      marquee: ["Danny vs Damian Cooper", "Logan Mathews closes in on Austin"],
      prestige:
        "The first major proving ground after AXF's latest power shifts, where reputations are tested before they can harden into authority.",
    },
    {
      name: "Saturday Night's Main Event",
      window: "Season Special",
      venue: "Broadcast Special",
      marquee: ["Elite spotlight matches", "Authority-level announcements"],
      prestige:
        "A special-event presentation built around spotlight attractions, television stakes, and major platform moments.",
    },
    {
      name: "Bad Blood",
      window: "Season Calendar",
      venue: "Venue to be announced",
      marquee: ["Personal grudges escalate", "Old alliances fracture under pressure"],
      prestige:
        "Where tension stops being political and becomes personal in front of the whole company.",
    },
    {
      name: "Money in the Bank",
      window: "Season Calendar",
      venue: "Venue to be announced",
      marquee: ["Career-changing opportunity", "World-title orbit intensifies"],
      prestige:
        "One of AXF's most volatile nights, designed to reward timing, nerve, and survival.",
    },
    {
      name: "SummerSlam — Night 1 & Night 2",
      window: "Two-Night Stadium Event",
      venue: "Stadium destination to be announced",
      marquee: ["Two nights of marquee collisions", "WrestleMania-level scale"],
      prestige:
        "A summer centerpiece built with stadium gravity, cinematic identity, and two nights of main-event scale.",
    },
    {
      name: "Clash at the Castle",
      window: "Global Destination",
      venue: "Venue to be announced",
      marquee: ["International showcase", "Championship and legacy pressure"],
      prestige:
        "A global stage that elevates every rivalry through atmosphere, prestige, and location.",
    },
    {
      name: "Crown Jewel",
      window: "Global Spectacle",
      venue: "Venue to be announced",
      marquee: ["Luxury presentation", "Super-fight atmosphere"],
      prestige:
        "AXF at its most opulent, theatrical, and headline-driven.",
    },
    {
      name: "Survivor Series",
      window: "Faction Warfare",
      venue: "Venue to be announced",
      marquee: ["Brand-defining conflict", "Control tested under team pressure"],
      prestige:
        "An event where power structures can crack because alliances finally have to hold under fire.",
    },
    {
      name: "Royal Rumble",
      window: "Road to WrestleMania",
      venue: "Venue to be announced",
      marquee: ["Thirty-entry chaos", "Dream-match season begins"],
      prestige:
        "The launch point for destiny, status, and stadium-level ambition.",
    },
    {
      name: "Elimination Chamber",
      window: "Road to WrestleMania",
      venue: "Venue to be announced",
      marquee: ["Steel structure pressure", "Championship pathways narrow"],
      prestige:
        "No event strips away comfort like the Chamber when every error echoes.",
    },
    {
      name: "WrestleMania",
      window: "Grandest Stage",
      venue: "Stadium destination to be announced",
      marquee: ["Career-defining history", "Main-event immortality"],
      prestige:
        "AXF's largest cultural stage, where legacies are measured under maximum pressure.",
    },
  ],
  news: [
    {
      category: "Authority",
      title: "Danny's influence reaches another level inside AXF's corporate hierarchy",
      summary:
        "The God of Reckoning is no longer merely impacting the card. His presence is now shaping the atmosphere around every major decision.",
      stamp: "AXF Desk",
    },
    {
      category: "Championship",
      title: "Austin remains the centerpiece of the title scene as Logan Mathews keeps advancing",
      summary:
        "The AXF Champion continues to operate with confidence, but the pressure from Logan Mathews is becoming impossible to dismiss.",
      stamp: "Official Report",
    },
    {
      category: "Backlash",
      title: "Damian Cooper's collision with Danny carries career-defining stakes",
      summary:
        "Damian's biggest test is no longer theoretical. Backlash now stands as the night he must answer for every promise attached to his rise.",
      stamp: "Event Center",
    },
    {
      category: "Mentorship",
      title: "Jayden's guidance remains central as Damian prepares for the biggest fight of the arc",
      summary:
        "With Jayden in his corner, Damian has experience, perspective, and pressure all moving in the same direction.",
      stamp: "AXF Feature",
    },
    {
      category: "Intercontinental",
      title: "Tyson Creed continues to define the Intercontinental Championship",
      summary:
        "The title is not being treated as a stepping stone. Tyson Creed is making it feel like a battleground for serious contenders.",
      stamp: "Championship Ledger",
    },
    {
      category: "History",
      title: "Camron Carter and Austin remain linked by old wounds and authority-era memory",
      summary:
        "No matter how the title picture shifts, the history between Camron Carter, Austin, and the structure around them refuses to disappear.",
      stamp: "AXF Archive",
    },
  ],
  storylines: [
    {
      id: "danny-power-rise",
      title: "Danny's CEO power rise",
      status: "Active weekly television arc",
      focus: "Danny vs authority power structure",
      copy:
        "Danny is not waiting for permission to become AXF's most important figure. He is leveraging legend, leverage, and fear to become the center of power without yet reaching full control. Every week the line between locker-room force and executive influence grows thinner.",
      beats: [
        "Danny's aura now extends beyond the ring and into the decision-making atmosphere of AXF.",
        "TKO-aligned influence sees him as both a threat and an inevitability.",
        "His rise is active, visible, and unfinished by Season 3 Episode 9.",
      ],
    },
    {
      id: "logan-vs-austin",
      title: "Logan Mathews vs Austin",
      status: "Current championship pressure arc",
      focus: "Top babyface challenger vs corporate heel champion",
      copy:
        "Austin has the title, the confidence, and the machinery around him. Logan Mathews has the momentum, the conviction, and the feeling of a future standard-bearer. This rivalry is about whether AXF's future belongs to the system or the man forcing the system to answer him.",
      beats: [
        "Austin projects authority with every appearance and treats challengers like problems to contain.",
        "Logan is framed as the next major face of AXF rather than a temporary obstacle.",
        "The rivalry is active now, not a distant endgame tease.",
      ],
    },
    {
      id: "damian-vs-danny",
      title: "Damian Cooper vs Danny at Backlash",
      status: "Immediate event arc",
      focus: "Mentored prospect vs complete final boss",
      copy:
        "Damian Cooper steps into Backlash carrying expectation, championship credibility, and the trust of Jayden. Danny stands on the other side as the company's benchmark for pressure. This is not about a future betrayal. It is about whether Damian can survive a test designed to expose every weakness.",
      beats: [
        "Damian remains a rising face champion rather than a rushed turn or collapse.",
        "Jayden's mentorship adds emotional and strategic weight to the confrontation.",
        "Danny treats the match like a measurement of the next generation's worth.",
      ],
    },
    {
      id: "jayden-damian",
      title: "Jayden and Damian Cooper",
      status: "Mentor-protege drama",
      focus: "Experience guiding potential",
      copy:
        "Jayden understands what it means to orbit Danny's legacy. That knowledge makes him the perfect guide for Damian Cooper, whose promise is real but whose biggest battles are arriving faster than most stars ever face them.",
      beats: [
        "Jayden's history with Danny gives every piece of advice extra meaning.",
        "Damian is being sharpened, not manipulated into a spoiler-heavy future turn.",
        "Their dynamic is one of belief, urgency, and high expectations.",
      ],
    },
    {
      id: "camron-austin-authority",
      title: "Camron Carter, Austin, and the authority shadow",
      status: "Ongoing background pressure",
      focus: "History tied to TKO Authority",
      copy:
        "Camron Carter does not need to force himself into the frame. His history with Austin and the authority environment around him makes every shared segment feel loaded before a word is spoken. That tension sits beneath the title picture and gives it a longer memory.",
      beats: [
        "Camron Carter's name and history are canonically protected throughout the site.",
        "The story strengthens Austin's position as a corporate heel rather than distracting from it.",
        "This remains an active current under AXF television rather than a resolved chapter.",
      ],
    },
  ],
  legends: [
    {
      name: "Danny",
      role: "Active legend",
      legacy: "A living benchmark whose championship history already belongs in company mythology.",
      moment: "Nine WrestleMania main events and a 12-time world-title resume that reshaped the standard.",
    },
    {
      name: "John Cena",
      role: "Retired icon",
      legacy: "A retired figure whose name remains part of AXF's legacy conversation without entering active booking.",
      moment: "Referenced only as a completed chapter of greatness inside the Hall of Legends.",
    },
    {
      name: "Jayden",
      role: "Generation-defining main eventer",
      legacy: "An all-time star whose connection to Danny gave AXF some of its deepest emotional history.",
      moment: "A career shaped by resilience, reinvention, and never fully escaping comparison to Danny.",
    },
    {
      name: "Austin",
      role: "Modern-era standard bearer",
      legacy: "A champion whose corporate-era dominance makes him impossible to ignore in the legacy archive.",
      moment: "The title reign that turned boardroom energy into headline heat.",
    },
  ],
  media: {
    titantron: [
      "Danny: God of Reckoning Entrance Package",
      "Austin: Corporate Standard Champion Open",
      "Logan Mathews: Punisher Spotlight",
    ],
    promos: [
      "Danny addresses the new balance of power",
      "Logan Mathews fires back at the champion",
      "Jayden prepares Damian Cooper for Backlash",
    ],
    highlights: [
      "Championship spotlight reel",
      "Main-event collisions of the current season",
      "AXF Gallery: defining moments so far",
    ],
    podcast: {
      title: "AXF WAR ROOM",
      summary:
        "A premium studio presentation breaking down authority shifts, championship pressure, and headline television arcs.",
    },
  },
  gallery: [
    {
      title: "Ringside authority",
      summary: "The tension around Danny feels bigger every time the camera gets closer.",
      image: "./assets/gallery/top-moment-1.png",
    },
    {
      title: "Champion's message",
      summary: "Austin's title presence remains calculated, polished, and threatening.",
      image: "./assets/gallery/top-moment-2.png",
    },
    {
      title: "The stare-down",
      summary: "Every face-off in AXF feels like the start of a documentary trailer.",
      image: "./assets/gallery/top-moment-3.png",
    },
    {
      title: "Blood and television light",
      summary: "AXF's best images look like war broadcast through prestige sports production.",
      image: "./assets/gallery/top-moment-4.png",
    },
    {
      title: "Title elevation",
      summary: "The Intercontinental Championship remains framed like a serious prize.",
      image: "./assets/gallery/top-moment-5.png",
    },
    {
      title: "Future in focus",
      summary: "Logan Mathews continues to be captured like the next man up.",
      image: "./assets/gallery/top-moment-6.png",
    },
  ],
  about: {
    history:
      "AXF was built as a global wrestling platform where sports entertainment, cinematic presentation, and championship prestige operate at the same level. Every show, event, and media property is designed to feel larger than television and closer to a premium sports-entertainment institution.",
    mission:
      "To create main-event level wrestling experiences where legacy, pressure, and spectacle meet in a single world-class brand.",
    vision:
      "To stand as the definitive global wrestling ecosystem, combining elite athletes, prestige storytelling, and broadcast-grade presentation.",
    leadership: [
      "AXF Executive Office",
      "Competition & Championship Operations",
      "Global Events and Premium Live Presentation",
      "Media, Broadcast, and Partnership Strategy",
    ],
    valhalla:
      "Valhalla Crown Studios, under Danny's ownership, represents AXF's expansion into premium storytelling, production identity, and the brand's larger cultural footprint. Its guiding phrase, 'Where Legends Are Forged,' is woven directly into AXF's broader presentation philosophy.",
  },
  contacts: [
    {
      department: "Business Inquiries",
      email: "partnerships@axf-global.com",
      focus: "Corporate relationships, licensing, and commercial strategy",
    },
    {
      department: "Sponsorships",
      email: "sponsorships@axf-global.com",
      focus: "Brand activations, event integrations, and premium campaigns",
    },
    {
      department: "Media Requests",
      email: "media@axf-global.com",
      focus: "Press coverage, interviews, credentials, and official statements",
    },
    {
      department: "Talent Relations",
      email: "talentrelations@axf-global.com",
      focus: "Roster logistics, appearances, and professional outreach",
    },
  ],
};
